; This dune file segment configures the build process for the project, 
; focusing on web bundling.

; This stanza excludes the 'node_modules' directory from being 
; considered by dune, which is a standard practice to prevent Dune from scanning 
; dependency files.
(dirs :standard \ node_modules)

; Build the Melange output as part of Dune's default `all` alias.
(alias
  (name all)
  (deps
    (alias_rec modern_sumerian_ocaml)))


; The 'melange.emit' block is used to compile ReasonML/OCaml code to JavaScript.
; - 'target output' specifies where the compiled JS files will be placed.
; - It relies on the 'app' library and compiles using specified module systems 
;   (here, es6 and mjs).
  (melange.emit
   (target output)
   (alias modern_sumerian_ocaml)
   (libraries app)
   (module_systems (es6 mjs))
   (runtime_deps 
    (glob_files_rec src/*.scss) 
    (glob_files_rec src/*.json)
    (glob_files_rec src/assets/*)
    (glob_files public/*)
    )
  )
